name: Run tests

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3

      - name: run tests
        run: g++ main.cpp tests/tests.cpp src/SquareMatrix.cpp -Wall && ./a.out
 